---
plugins:
  - react
  - jsx-a11y
  - import
  - prettier
extends:
- airbnb
- plugin:react/recommended
- prettier/react
- plugin:prettier/recommended
env:
  browser: true
  commonjs: true
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
    globalReturn: true
    impliedStrict: true
    experimentalDecorators: true
rules:
  comma-dangle: 0
  no-underscore-dangle: 0
  arrow-parens: 0
  jsx-a11y/href-no-hash: 0
  react/jsx-filename-extension: 0
  no-plusplus: 0
  no-console: 0
  camelcase: 1
  react/state-in-constructor: 0
  # Ratchet these down over time
  react/jsx-fragments: 1
  react/prop-types: 0
  react/destructuring-assignment: 0
  react/jsx-props-no-spreading: 0
  react/require-default-props: 1
  jsx-a11y/anchor-is-valid: 1
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  import/no-named-as-default: 1
  react/prefer-stateless-function: 1
  react/forbid-prop-types: 1
  react/display-name: 1
  react/button-has-type: 0
  class-methods-use-this: 0
settings:
  react:
    pragma: React
    version: "16.9.0"